language: python
python: 2.7
sudo: false
cache:
  directories:
    - eggs
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout annotate
  - bin/buildout -Nq
before_script:
  - firefox -v
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
